spring.application.name=MsAuth
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/gestman?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.template.retry.enabled=true


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Configuración JWT
jwt.secret=00001111222233334444

jwt.expiration=43200000